package com.umur.modernjava.ch19;

import java.io.IOException;
import java.io.InputStream;
import java.lang.classfile.ClassBuilder;
import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.lang.classfile.ClassTransform;
import java.lang.classfile.MethodModel;
import java.lang.constant.ClassDesc;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.InvocationTargetException;

/**
 * Class-File API examples for Chapter 19.
 *
 * Walks through three demos: reading a class file (parse and inspect
 * java.lang.String's bytecode), writing a class from scratch (a Sum class with
 * a static int sum(int,int) method), and transforming a class (add a method
 * to an existing class via ClassTransform).
 *
 * The Class-File API lives in java.lang.classfile. As of Java 24 it is final
 * and lives in the java.base module: no preview flag, no add-modules flag.
 * Run with plain `mvn -q clean compile exec:java`.
 */
public final class ClassFileApiExamples {

    private ClassFileApiExamples() {
        // utility
    }

    public static void main(String[] args) throws Throwable {
        runReadingDemo();
        runWritingDemo();
        runTransformingDemo();
    }

    // -------- demo 1: parse and inspect a real class file --------

    private static void runReadingDemo() throws IOException {
        System.out.println("[demo 1] reading: parse java.lang.String's class file");

        byte[] bytes = readClassBytesFromRuntime(String.class);
        ClassModel model = ClassFile.of().parse(bytes);

        System.out.println("  class name        = " + model.thisClass().asInternalName());
        System.out.println("  superclass        = " + model.superclass()
                .map(ce -> ce.asInternalName()).orElse("(none)"));
        System.out.println("  interface count   = " + model.interfaces().size());
        System.out.println("  declared methods  = " + model.methods().size());
        System.out.println("  total bytes       = " + bytes.length);
        System.out.println("  major version     = " + model.majorVersion());

        System.out.println("  first 10 methods:");
        int shown = 0;
        for (MethodModel method : model.methods()) {
            if (shown >= 10) {
                break;
            }
            System.out.println("    " + method.methodName().stringValue()
                    + method.methodType().stringValue());
            shown++;
        }
        System.out.println();
    }

    private static byte[] readClassBytesFromRuntime(Class<?> cls) throws IOException {
        String resource = cls.getName().replace('.', '/') + ".class";
        try (InputStream in = cls.getClassLoader() == null
                ? ClassLoader.getSystemResourceAsStream(resource)
                : cls.getClassLoader().getResourceAsStream(resource)) {
            if (in == null) {
                throw new IOException("could not locate class resource: " + resource);
            }
            return in.readAllBytes();
        }
    }

    // -------- demo 2: build a class from scratch and execute it --------

    private static void runWritingDemo() throws Throwable {
        System.out.println("[demo 2] writing: generate Sum.sum(int, int) from scratch");

        ClassDesc generatedName = ClassDesc.of(
                "com.umur.modernjava.ch19.Sum");
        ClassDesc intType = ClassDesc.ofDescriptor("I");
        MethodTypeDesc sumDescriptor = MethodTypeDesc.of(intType, intType, intType);

        byte[] generated = ClassFile.of().build(generatedName,
                (ClassBuilder cb) -> {
                    cb.withFlags(ClassFile.ACC_PUBLIC | ClassFile.ACC_FINAL);
                    cb.withMethod(
                            "sum",
                            sumDescriptor,
                            ClassFile.ACC_PUBLIC | ClassFile.ACC_STATIC,
                            mb -> mb.withCode(code -> code
                                    .iload(0)
                                    .iload(1)
                                    .iadd()
                                    .ireturn()));
                });

        System.out.println("  generated class   = " + generatedName.descriptorString());
        System.out.println("  generated bytes   = " + generated.length);

        // Defining the class needs a Lookup whose package matches the generated
        // class. The simplest way is to forward to the running class's lookup.
        MethodHandles.Lookup lookup = MethodHandles.lookup();
        Class<?> definedSum = lookup.defineClass(generated);

        try {
            int result = (int) definedSum
                    .getMethod("sum", int.class, int.class)
                    .invoke(null, 17, 25);
            System.out.println("  Sum.sum(17, 25)   = " + result);
        } catch (InvocationTargetException e) {
            throw e.getCause();
        }
        System.out.println();
    }

    // -------- demo 3: transform a class to add a new method --------

    private static void runTransformingDemo() throws Throwable {
        System.out.println("[demo 3] transforming: add a method to an existing class");

        ClassDesc baseName = ClassDesc.of(
                "com.umur.modernjava.ch19.Greeter");
        ClassDesc voidType = ClassDesc.ofDescriptor("V");
        ClassDesc stringType = ClassDesc.of("java.lang.String");
        ClassDesc intType = ClassDesc.ofDescriptor("I");

        // Step A: build a small base class with a single static method.
        byte[] baseBytes = ClassFile.of().build(baseName, cb -> {
            cb.withFlags(ClassFile.ACC_PUBLIC | ClassFile.ACC_FINAL);
            cb.withMethod(
                    "ageNextYear",
                    MethodTypeDesc.of(intType, intType),
                    ClassFile.ACC_PUBLIC | ClassFile.ACC_STATIC,
                    mb -> mb.withCode(code -> code
                            .iload(0)
                            .iconst_1()
                            .iadd()
                            .ireturn()));
        });

        ClassModel baseModel = ClassFile.of().parse(baseBytes);
        System.out.println("  base bytes        = " + baseBytes.length);
        System.out.println("  base method count = " + baseModel.methods().size());

        // Step B: a no-op transform that copies every element through, then an
        // end handler that appends a new method.
        ClassTransform passThrough = (classBuilder, classElement) ->
                classBuilder.with(classElement);

        ClassTransform addGreet = passThrough.andThen(
                ClassTransform.endHandler(classBuilder ->
                        classBuilder.withMethod(
                                "greet",
                                MethodTypeDesc.of(stringType),
                                ClassFile.ACC_PUBLIC | ClassFile.ACC_STATIC,
                                mb -> mb.withCode(code -> code
                                        .ldc("hello from a transformed class")
                                        .areturn()))));

        byte[] transformedBytes = ClassFile.of()
                .transformClass(baseModel, addGreet);

        ClassModel transformedModel = ClassFile.of().parse(transformedBytes);
        System.out.println("  transformed bytes = " + transformedBytes.length);
        System.out.println("  transformed count = " + transformedModel.methods().size());

        MethodHandles.Lookup lookup = MethodHandles.lookup();
        Class<?> defined = lookup.defineClass(transformedBytes);

        try {
            int aged = (int) defined.getMethod("ageNextYear", int.class)
                    .invoke(null, 41);
            String greeting = (String) defined.getMethod("greet").invoke(null);
            System.out.println("  ageNextYear(41)   = " + aged);
            System.out.println("  greet()           = " + greeting);
        } catch (InvocationTargetException e) {
            throw e.getCause();
        }
        System.out.println();
    }
}
